/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SessionLogRouteImport } from './routes/session-log'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as CreateSubagentRouteImport } from './routes/create-subagent'
import { Route as CreateSkillRouteImport } from './routes/create-skill'
import { Route as CreatePluginRouteImport } from './routes/create-plugin'
import { Route as CreateMarketplaceRouteImport } from './routes/create-marketplace'
import { Route as AgentsFrameworkKickstarterRouteImport } from './routes/agents-framework-kickstarter'
import { Route as AfkTasksRouteImport } from './routes/afk-tasks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionLogStreamRouteImport } from './routes/api/session-log-stream'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLogRoute = SessionLogRouteImport.update({
  id: '/session-log',
  path: '/session-log',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSubagentRoute = CreateSubagentRouteImport.update({
  id: '/create-subagent',
  path: '/create-subagent',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSkillRoute = CreateSkillRouteImport.update({
  id: '/create-skill',
  path: '/create-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePluginRoute = CreatePluginRouteImport.update({
  id: '/create-plugin',
  path: '/create-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMarketplaceRoute = CreateMarketplaceRouteImport.update({
  id: '/create-marketplace',
  path: '/create-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsFrameworkKickstarterRoute =
  AgentsFrameworkKickstarterRouteImport.update({
    id: '/agents-framework-kickstarter',
    path: '/agents-framework-kickstarter',
    getParentRoute: () => rootRouteImport,
  } as any)
const AfkTasksRoute = AfkTasksRouteImport.update({
  id: '/afk-tasks',
  path: '/afk-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionLogStreamRoute = ApiSessionLogStreamRouteImport.update({
  id: '/api/session-log-stream',
  path: '/api/session-log-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afk-tasks': typeof AfkTasksRoute
  '/agents-framework-kickstarter': typeof AgentsFrameworkKickstarterRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
  '/api/session-log-stream': typeof ApiSessionLogStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afk-tasks': typeof AfkTasksRoute
  '/agents-framework-kickstarter': typeof AgentsFrameworkKickstarterRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
  '/api/session-log-stream': typeof ApiSessionLogStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afk-tasks': typeof AfkTasksRoute
  '/agents-framework-kickstarter': typeof AgentsFrameworkKickstarterRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
  '/api/session-log-stream': typeof ApiSessionLogStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afk-tasks'
    | '/agents-framework-kickstarter'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/rules'
    | '/session-log'
    | '/workflows'
    | '/api/session-log-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afk-tasks'
    | '/agents-framework-kickstarter'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/rules'
    | '/session-log'
    | '/workflows'
    | '/api/session-log-stream'
  id:
    | '__root__'
    | '/'
    | '/afk-tasks'
    | '/agents-framework-kickstarter'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/rules'
    | '/session-log'
    | '/workflows'
    | '/api/session-log-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfkTasksRoute: typeof AfkTasksRoute
  AgentsFrameworkKickstarterRoute: typeof AgentsFrameworkKickstarterRoute
  CreateMarketplaceRoute: typeof CreateMarketplaceRoute
  CreatePluginRoute: typeof CreatePluginRoute
  CreateSkillRoute: typeof CreateSkillRoute
  CreateSubagentRoute: typeof CreateSubagentRoute
  RulesRoute: typeof RulesRoute
  SessionLogRoute: typeof SessionLogRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiSessionLogStreamRoute: typeof ApiSessionLogStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-log': {
      id: '/session-log'
      path: '/session-log'
      fullPath: '/session-log'
      preLoaderRoute: typeof SessionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-subagent': {
      id: '/create-subagent'
      path: '/create-subagent'
      fullPath: '/create-subagent'
      preLoaderRoute: typeof CreateSubagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-skill': {
      id: '/create-skill'
      path: '/create-skill'
      fullPath: '/create-skill'
      preLoaderRoute: typeof CreateSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-plugin': {
      id: '/create-plugin'
      path: '/create-plugin'
      fullPath: '/create-plugin'
      preLoaderRoute: typeof CreatePluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-marketplace': {
      id: '/create-marketplace'
      path: '/create-marketplace'
      fullPath: '/create-marketplace'
      preLoaderRoute: typeof CreateMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-framework-kickstarter': {
      id: '/agents-framework-kickstarter'
      path: '/agents-framework-kickstarter'
      fullPath: '/agents-framework-kickstarter'
      preLoaderRoute: typeof AgentsFrameworkKickstarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afk-tasks': {
      id: '/afk-tasks'
      path: '/afk-tasks'
      fullPath: '/afk-tasks'
      preLoaderRoute: typeof AfkTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-log-stream': {
      id: '/api/session-log-stream'
      path: '/api/session-log-stream'
      fullPath: '/api/session-log-stream'
      preLoaderRoute: typeof ApiSessionLogStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfkTasksRoute: AfkTasksRoute,
  AgentsFrameworkKickstarterRoute: AgentsFrameworkKickstarterRoute,
  CreateMarketplaceRoute: CreateMarketplaceRoute,
  CreatePluginRoute: CreatePluginRoute,
  CreateSkillRoute: CreateSkillRoute,
  CreateSubagentRoute: CreateSubagentRoute,
  RulesRoute: RulesRoute,
  SessionLogRoute: SessionLogRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiSessionLogStreamRoute: ApiSessionLogStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
