// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "code-crawler",
  DESCRIPTION: "A MCP server to crawl code repositories and extract information about the codebase.",
  REPOSITORY: "https://github.com/lichens-innovation/ai-dev-tools",
  AUTHOR: "Lichens Innovation",
  VERSION: "0.0.1",
  VERSION_DATE: "2026-04-08",
  VERSION_DATE_ISO: "2026-04-08T14:56:42.655Z",
});

export const LONG_VERSION_DATE = "0.0.1 (2026-04-08)";
