import { readFileSync, writeFileSync } from "node:fs";
import { input } from "@inquirer/prompts";

const packageJsonPath = "./package.json";
const constantsFilename = "./src/constants.ts";

const readPackageJson = () => {
  const content = readFileSync(packageJsonPath, { encoding: "utf8" });
  return JSON.parse(content);
};

const writePackageJson = (packageData) => {
  writeFileSync(packageJsonPath, JSON.stringify(packageData, null, 2) + "\n", {
    encoding: "utf8",
  });
};

const promptVersion = async (currentVersion) => {
  const answer = await input({
    message: `Current version: ${currentVersion}\nNew version (Enter to keep)`,
    default: currentVersion,
  });
  const trimmed = answer.trim();
  return trimmed || currentVersion;
};

const generateConstantsFile = (packageMetadata) => {
  const { name, description, version, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split("T")[0];

  return `// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: ${JSON.stringify(name)},
  DESCRIPTION: ${JSON.stringify(description)},
  REPOSITORY: ${JSON.stringify(repository)},
  AUTHOR: ${JSON.stringify(author)},
  VERSION: ${JSON.stringify(version)},
  VERSION_DATE: ${JSON.stringify(dateOnly)},
  VERSION_DATE_ISO: ${JSON.stringify(dateIso)},
});

export const LONG_VERSION_DATE = ${JSON.stringify(`${version} (${dateOnly})`)};
`;
};

const createUpdatedPackageMetadata = (packageMetadata, newVersion) => {
  const newPackageMetadata = { ...packageMetadata, version: newVersion };
  console.info(`\t- Updating package.json with version "${newVersion}"...`);
  writePackageJson(newPackageMetadata);
  console.info(`\t- package.json updated successfully.`);

  return newPackageMetadata;
};

const main = async () => {
  console.info("\t[Version generator script]");

  try {
    let packageMetadata = readPackageJson();
    const currentVersion = packageMetadata.version;

    const newVersion = await promptVersion(currentVersion);
    if (newVersion !== currentVersion) {
      packageMetadata = createUpdatedPackageMetadata(packageMetadata, newVersion);
    } else {
      console.info(`\t- Version unchanged: ${currentVersion}`);
    }

    const data = generateConstantsFile(packageMetadata);
    console.info(`\t- Writing file "${constantsFilename}"...`, packageMetadata.version);
    writeFileSync(constantsFilename, data, { encoding: "utf8" });
    console.info(`\t- File "${constantsFilename}" written successfully.`);
  } catch (err) {
    console.error(`\t- Error: ${err.message}`, err);
    process.exit(1);
  }
};

main();
