import { readFileSync, writeFileSync } from "node:fs";
import { input } from "@inquirer/prompts";

const packageJsonPath = "./package.json";
const versionGenFilename = "./src/version.gen.ts";

type PackageJsonData = {
  name: string;
  description: string;
  version: string;
  author: string;
  repository: unknown;
  [key: string]: unknown;
};

const readPackageJson = (): PackageJsonData => {
  const content = readFileSync(packageJsonPath, { encoding: "utf8" });
  return JSON.parse(content) as PackageJsonData;
};

const writePackageJson = (packageData: PackageJsonData): void => {
  writeFileSync(packageJsonPath, JSON.stringify(packageData, null, 2) + "\n", {
    encoding: "utf8",
  });
};

const promptVersion = async (currentVersion: string): Promise<string> => {
  const answer = await input({
    message: `Current version: ${currentVersion}\nNew version (Enter to keep)`,
    default: currentVersion,
  });
  const trimmed = answer.trim();
  return trimmed || currentVersion;
};

const generateConstantsFile = (packageMetadata: PackageJsonData): string => {
  const { name, description, version, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split("T")[0];

  return `// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.ts
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: ${JSON.stringify(name)},
  DESCRIPTION: ${JSON.stringify(description)},
  REPOSITORY: ${JSON.stringify(repository)},
  AUTHOR: ${JSON.stringify(author)},
  VERSION: ${JSON.stringify(version)},
  VERSION_DATE: ${JSON.stringify(dateOnly)},
  VERSION_DATE_ISO: ${JSON.stringify(dateIso)},
});

export const LONG_VERSION_DATE = ${JSON.stringify(`${version} (${dateOnly})`)};
`;
};

interface CreateUpdatedPackageMetadataArgs {
  packageMetadata: PackageJsonData;
  newVersion: string;
}

const createUpdatedPackageMetadata = ({
  packageMetadata,
  newVersion,
}: CreateUpdatedPackageMetadataArgs): PackageJsonData => {
  const newPackageMetadata = { ...packageMetadata, version: newVersion };
  console.info(`[createUpdatedPackageMetadata] Updating package.json with version "${newVersion}"...`);
  writePackageJson(newPackageMetadata);
  console.info("[createUpdatedPackageMetadata] package.json updated successfully.");

  return newPackageMetadata;
};

const main = async (): Promise<void> => {
  console.info("[main] Version generator script");

  try {
    let packageMetadata = readPackageJson();
    const currentVersion = packageMetadata.version;

    const newVersion = await promptVersion(currentVersion);
    if (newVersion !== currentVersion) {
      packageMetadata = createUpdatedPackageMetadata({
        packageMetadata,
        newVersion,
      });
    } else {
      console.info(`[main] Version unchanged: ${currentVersion}`);
    }

    const data = generateConstantsFile(packageMetadata);
    console.info(`[main] Writing file "${versionGenFilename}" for version ${packageMetadata.version}...`);
    writeFileSync(versionGenFilename, data, { encoding: "utf8" });
    console.info(`[main] File "${versionGenFilename}" written successfully.`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[main] Error: ${message}`, err);
    process.exit(1);
  }
};

void main();
