/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenderSplatRouteImport } from './routes/render.$'
import { Route as ApiSelectionRouteImport } from './routes/api.selection'
import { Route as PagesKindNameRouteImport } from './routes/pages.$kind.$name'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderSplatRoute = RenderSplatRouteImport.update({
  id: '/render/$',
  path: '/render/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelectionRoute = ApiSelectionRouteImport.update({
  id: '/api/selection',
  path: '/api/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesKindNameRoute = PagesKindNameRouteImport.update({
  id: '/pages/$kind/$name',
  path: '/pages/$kind/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/api/selection': typeof ApiSelectionRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/api/selection': typeof ApiSelectionRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/api/selection': typeof ApiSelectionRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/mcp'
    | '/api/selection'
    | '/render/$'
    | '/pages/$kind/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/mcp'
    | '/api/selection'
    | '/render/$'
    | '/pages/$kind/$name'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/mcp'
    | '/api/selection'
    | '/render/$'
    | '/pages/$kind/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  McpRoute: typeof McpRoute
  ApiSelectionRoute: typeof ApiSelectionRoute
  RenderSplatRoute: typeof RenderSplatRoute
  PagesKindNameRoute: typeof PagesKindNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$': {
      id: '/render/$'
      path: '/render/$'
      fullPath: '/render/$'
      preLoaderRoute: typeof RenderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selection': {
      id: '/api/selection'
      path: '/api/selection'
      fullPath: '/api/selection'
      preLoaderRoute: typeof ApiSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$kind/$name': {
      id: '/pages/$kind/$name'
      path: '/pages/$kind/$name'
      fullPath: '/pages/$kind/$name'
      preLoaderRoute: typeof PagesKindNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  McpRoute: McpRoute,
  ApiSelectionRoute: ApiSelectionRoute,
  RenderSplatRoute: RenderSplatRoute,
  PagesKindNameRoute: PagesKindNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
