/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailwindRouteImport } from './routes/tailwind'
import { Route as PaletteRouteImport } from './routes/palette'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenderSplatRouteImport } from './routes/render.$'
import { Route as ExcalidrawAssetsSplatRouteImport } from './routes/excalidraw-assets.$'
import { Route as ApiSelectionRouteImport } from './routes/api.selection'
import { Route as ApiRequestsRouteImport } from './routes/api.requests'
import { Route as PagesKindNameRouteImport } from './routes/pages.$kind.$name'
import { Route as ApiRequestsIdSentRouteImport } from './routes/api.requests.$id.sent'

const TailwindRoute = TailwindRouteImport.update({
  id: '/tailwind',
  path: '/tailwind',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteRoute = PaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderSplatRoute = RenderSplatRouteImport.update({
  id: '/render/$',
  path: '/render/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcalidrawAssetsSplatRoute = ExcalidrawAssetsSplatRouteImport.update({
  id: '/excalidraw-assets/$',
  path: '/excalidraw-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelectionRoute = ApiSelectionRouteImport.update({
  id: '/api/selection',
  path: '/api/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesKindNameRoute = PagesKindNameRouteImport.update({
  id: '/pages/$kind/$name',
  path: '/pages/$kind/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdSentRoute = ApiRequestsIdSentRouteImport.update({
  id: '/$id/sent',
  path: '/$id/sent',
  getParentRoute: () => ApiRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/palette': typeof PaletteRoute
  '/tailwind': typeof TailwindRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/selection': typeof ApiSelectionRoute
  '/excalidraw-assets/$': typeof ExcalidrawAssetsSplatRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
  '/api/requests/$id/sent': typeof ApiRequestsIdSentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/palette': typeof PaletteRoute
  '/tailwind': typeof TailwindRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/selection': typeof ApiSelectionRoute
  '/excalidraw-assets/$': typeof ExcalidrawAssetsSplatRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
  '/api/requests/$id/sent': typeof ApiRequestsIdSentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/palette': typeof PaletteRoute
  '/tailwind': typeof TailwindRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/selection': typeof ApiSelectionRoute
  '/excalidraw-assets/$': typeof ExcalidrawAssetsSplatRoute
  '/render/$': typeof RenderSplatRoute
  '/pages/$kind/$name': typeof PagesKindNameRoute
  '/api/requests/$id/sent': typeof ApiRequestsIdSentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/mcp'
    | '/palette'
    | '/tailwind'
    | '/api/requests'
    | '/api/selection'
    | '/excalidraw-assets/$'
    | '/render/$'
    | '/pages/$kind/$name'
    | '/api/requests/$id/sent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/mcp'
    | '/palette'
    | '/tailwind'
    | '/api/requests'
    | '/api/selection'
    | '/excalidraw-assets/$'
    | '/render/$'
    | '/pages/$kind/$name'
    | '/api/requests/$id/sent'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/mcp'
    | '/palette'
    | '/tailwind'
    | '/api/requests'
    | '/api/selection'
    | '/excalidraw-assets/$'
    | '/render/$'
    | '/pages/$kind/$name'
    | '/api/requests/$id/sent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  McpRoute: typeof McpRoute
  PaletteRoute: typeof PaletteRoute
  TailwindRoute: typeof TailwindRoute
  ApiRequestsRoute: typeof ApiRequestsRouteWithChildren
  ApiSelectionRoute: typeof ApiSelectionRoute
  ExcalidrawAssetsSplatRoute: typeof ExcalidrawAssetsSplatRoute
  RenderSplatRoute: typeof RenderSplatRoute
  PagesKindNameRoute: typeof PagesKindNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailwind': {
      id: '/tailwind'
      path: '/tailwind'
      fullPath: '/tailwind'
      preLoaderRoute: typeof TailwindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$': {
      id: '/render/$'
      path: '/render/$'
      fullPath: '/render/$'
      preLoaderRoute: typeof RenderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excalidraw-assets/$': {
      id: '/excalidraw-assets/$'
      path: '/excalidraw-assets/$'
      fullPath: '/excalidraw-assets/$'
      preLoaderRoute: typeof ExcalidrawAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selection': {
      id: '/api/selection'
      path: '/api/selection'
      fullPath: '/api/selection'
      preLoaderRoute: typeof ApiSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$kind/$name': {
      id: '/pages/$kind/$name'
      path: '/pages/$kind/$name'
      fullPath: '/pages/$kind/$name'
      preLoaderRoute: typeof PagesKindNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id/sent': {
      id: '/api/requests/$id/sent'
      path: '/$id/sent'
      fullPath: '/api/requests/$id/sent'
      preLoaderRoute: typeof ApiRequestsIdSentRouteImport
      parentRoute: typeof ApiRequestsRoute
    }
  }
}

interface ApiRequestsRouteChildren {
  ApiRequestsIdSentRoute: typeof ApiRequestsIdSentRoute
}

const ApiRequestsRouteChildren: ApiRequestsRouteChildren = {
  ApiRequestsIdSentRoute: ApiRequestsIdSentRoute,
}

const ApiRequestsRouteWithChildren = ApiRequestsRoute._addFileChildren(
  ApiRequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  McpRoute: McpRoute,
  PaletteRoute: PaletteRoute,
  TailwindRoute: TailwindRoute,
  ApiRequestsRoute: ApiRequestsRouteWithChildren,
  ApiSelectionRoute: ApiSelectionRoute,
  ExcalidrawAssetsSplatRoute: ExcalidrawAssetsSplatRoute,
  RenderSplatRoute: RenderSplatRoute,
  PagesKindNameRoute: PagesKindNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
