/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SessionLogRouteImport } from './routes/session-log'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as MaestroTasksRouteImport } from './routes/maestro-tasks'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLogRoute = SessionLogRouteImport.update({
  id: '/session-log',
  path: '/session-log',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroTasksRoute = MaestroTasksRouteImport.update({
  id: '/maestro-tasks',
  path: '/maestro-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maestro-tasks' | '/rules' | '/session-log' | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maestro-tasks' | '/rules' | '/session-log' | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaestroTasksRoute: typeof MaestroTasksRoute
  RulesRoute: typeof RulesRoute
  SessionLogRoute: typeof SessionLogRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-log': {
      id: '/session-log'
      path: '/session-log'
      fullPath: '/session-log'
      preLoaderRoute: typeof SessionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro-tasks': {
      id: '/maestro-tasks'
      path: '/maestro-tasks'
      fullPath: '/maestro-tasks'
      preLoaderRoute: typeof MaestroTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaestroTasksRoute: MaestroTasksRoute,
  RulesRoute: RulesRoute,
  SessionLogRoute: SessionLogRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
