/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SessionLogRouteImport } from './routes/session-log'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as MaestroTasksRouteImport } from './routes/maestro-tasks'
import { Route as InstallRouteImport } from './routes/install'
import { Route as CreateSubagentRouteImport } from './routes/create-subagent'
import { Route as CreateSkillRouteImport } from './routes/create-skill'
import { Route as CreatePluginRouteImport } from './routes/create-plugin'
import { Route as CreateMarketplaceRouteImport } from './routes/create-marketplace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLogRoute = SessionLogRouteImport.update({
  id: '/session-log',
  path: '/session-log',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroTasksRoute = MaestroTasksRouteImport.update({
  id: '/maestro-tasks',
  path: '/maestro-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSubagentRoute = CreateSubagentRouteImport.update({
  id: '/create-subagent',
  path: '/create-subagent',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSkillRoute = CreateSkillRouteImport.update({
  id: '/create-skill',
  path: '/create-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePluginRoute = CreatePluginRouteImport.update({
  id: '/create-plugin',
  path: '/create-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMarketplaceRoute = CreateMarketplaceRouteImport.update({
  id: '/create-marketplace',
  path: '/create-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/install': typeof InstallRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/install': typeof InstallRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/install': typeof InstallRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/install'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/tools'
    | '/workflows'
    | '/docs/$slug'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/install'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/tools'
    | '/workflows'
    | '/docs/$slug'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/install'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/tools'
    | '/workflows'
    | '/docs/$slug'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateMarketplaceRoute: typeof CreateMarketplaceRoute
  CreatePluginRoute: typeof CreatePluginRoute
  CreateSkillRoute: typeof CreateSkillRoute
  CreateSubagentRoute: typeof CreateSubagentRoute
  InstallRoute: typeof InstallRoute
  MaestroTasksRoute: typeof MaestroTasksRoute
  RulesRoute: typeof RulesRoute
  SessionLogRoute: typeof SessionLogRoute
  ToolsRoute: typeof ToolsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-log': {
      id: '/session-log'
      path: '/session-log'
      fullPath: '/session-log'
      preLoaderRoute: typeof SessionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro-tasks': {
      id: '/maestro-tasks'
      path: '/maestro-tasks'
      fullPath: '/maestro-tasks'
      preLoaderRoute: typeof MaestroTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-subagent': {
      id: '/create-subagent'
      path: '/create-subagent'
      fullPath: '/create-subagent'
      preLoaderRoute: typeof CreateSubagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-skill': {
      id: '/create-skill'
      path: '/create-skill'
      fullPath: '/create-skill'
      preLoaderRoute: typeof CreateSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-plugin': {
      id: '/create-plugin'
      path: '/create-plugin'
      fullPath: '/create-plugin'
      preLoaderRoute: typeof CreatePluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-marketplace': {
      id: '/create-marketplace'
      path: '/create-marketplace'
      fullPath: '/create-marketplace'
      preLoaderRoute: typeof CreateMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateMarketplaceRoute: CreateMarketplaceRoute,
  CreatePluginRoute: CreatePluginRoute,
  CreateSkillRoute: CreateSkillRoute,
  CreateSubagentRoute: CreateSubagentRoute,
  InstallRoute: InstallRoute,
  MaestroTasksRoute: MaestroTasksRoute,
  RulesRoute: RulesRoute,
  SessionLogRoute: SessionLogRoute,
  ToolsRoute: ToolsRoute,
  WorkflowsRoute: WorkflowsRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
